### ISSUE TITLE
Mod loader issue 

### ISSUE THREAD

**Issue by jeproxx1** [Spacehaven-modding-tools/spacehaven-modloader#19] opened 2021-05-19 05:22 UTC
Hey, kinda new to this. 
I'm constantly getting this error whenever I use any "zero system point" mod. I don't know if this is a mod issue or a mod loader issue. Hoping for you to shed some light on it. 
Thanks!
![image](https://user-images.githubusercontent.com/84433945/118760337-339d6600-b8a5-11eb-810b-b4a69581ba39.png)

**Comment by WalterLPearson** [comment] 2021-06-04 15:05
Duplicate of "Possible issue during CIM generation" #5.
This is fixed in the next release.

**Closed by WalterLPearson** 2021-06-04 15:05 UTC
